# Generated by Django 3.2.12 on 2025-01-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Created_PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='作成したPDF名', max_length=100)),
                ('description', models.TextField(blank=True, help_text='作成したPDFを説明する文章（任意）', null=True)),
                ('file_path', models.FileField(upload_to='pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新日時', null=True)),
                ('delete_flag', models.BooleanField(help_text='論理削除用フラッグ', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
