# Generated by Django 3.2.12 on 2025-01-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acrobat_paro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
